# Generated by Django 3.2 on 2021-04-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
